# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s64MsPE4_AOWnOEXLG9cnXOXzcBUosh0
"""

import cv2
from google.colab.patches import cv2_imshow


image = cv2.imread('/content/photo_2024-11-29_18-01-45.jpg')

flipped_horizontal = cv2.flip(image, 1)


cv2_imshow(image)
cv2_imshow(flipped_horizontal)

import cv2
from google.colab.patches import cv2_imshow

image = cv2.imread('/content/photo_2024-11-29_18-01-45.jpg')


flipped_vertical = cv2.flip(image, 0)

cv2_imshow(image)
cv2_imshow(flipped_vertical)
cv2.waitKey(0)
cv2.destroyAllWindows()



import cv2
import numpy as np
from google.colab.patches import cv2_imshow


image = cv2.imread('/content/photo_2024-11-29_18-01-45.jpg')

(h, w) = image.shape[:2]
center = (w // 2, h // 2)


angle = 45
scale = 1.0
rotation_matrix = cv2.getRotationMatrix2D(center, angle, scale)

rotated_image = cv2.warpAffine(image, rotation_matrix, (w, h))

cv2_imshow(image)
cv2_imshow(rotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

import cv2
from google.colab.patches import cv2_imshow

image = cv2.imread('/content/photo_2024-11-29_18-01-45.jpg')

zoom_factor = 1.3

(h, w) = image.shape[:2]

zoomed_image = cv2.resize(image, None, fx=zoom_factor, fy=zoom_factor, interpolation=cv2.INTER_LINEAR)

start_x = (zoomed_image.shape[1] - w) // 2
start_y = (zoomed_image.shape[0] - h) // 2
cropped_image = zoomed_image[start_y:start_y+h, start_x:start_x+w]

cv2_imshow(image)
cv2_imshow(cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()